# Generated by Django 2.2.1 on 2019-05-26 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movieID', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
                ('genres', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='UserRankingMovie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.IntegerField()),
                ('movieId', models.IntegerField()),
                ('rating', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('movies_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='recommendation.Movies')),
            ],
            bases=('recommendation.movies',),
        ),
        migrations.CreateModel(
            name='MovieUser',
            fields=[
                ('movies_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='recommendation.Movies')),
            ],
            bases=('recommendation.movies',),
        ),
    ]
